# Generated by Django 4.1.4 on 2022-12-12 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushitypecomment',
            name='comment',
            field=models.TextField(blank=True, max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
