# Generated by Django 4.1.4 on 2022-12-09 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sushi_lover.core.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('username', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sushi_lover.core.utilities.image_upload_location)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
