# Generated by Django 4.1.4 on 2022-12-10 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_appprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16, 'You must be 16 years old or above.')]),
        ),
    ]
